package models;

public enum Screen {
    START,
    LOCAL_OPTION,
    LOCATION_SETTING,
    REMOTE_LOCATION_SETTING,
    REMOTE_TCP_OPTION,
    REMOTE_UDP_OPTION,
    USER_FORM,
    GAME_PANEL,
    LEVEL_OPTION
}
